version: '3.8'

services:
  booksell_postgresql:
    image: postgres:16
    container_name: booksell_postgresql
    volumes:
      - booksell_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - booksell_network

volumes:
  booksell_postgresql:
    external: true

networks:
  booksell_network:
    external: true
