version: '3.8'

services:
  store_of_book:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/store_of_book
    restart: always
    ports:
      - "8000:8000"
    networks:
      - shared_network
    depends_on:
      - booksell_postgresql

  booksell_postgresql:
    image: registry.sedrehgroup.ir/postgres:latest
    container_name: booksell_postgresql
    volumes:
      - booksell_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - shared_network

volumes:
  booksell_postgresql:
    external: true

networks:
  shared_network:
    external: true
