# Generated by Django 5.0.4 on 2024-05-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
